-- Adminer 4.8.4 MySQL 9.0.1 dump

SET NAMES utf8;
SET time_zone = '+00:00';
SET foreign_key_checks = 0;
SET sql_mode = 'NO_AUTO_VALUE_ON_ZERO';

SET NAMES utf8mb4;

DROP TABLE IF EXISTS `posts`;
CREATE TABLE `posts` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `title` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `slug` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `content` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `excerpt` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `user_id` bigint unsigned NOT NULL,
  `featured_image` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `is_published` tinyint(1) NOT NULL DEFAULT '0',
  `published_at` timestamp NULL DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `posts_slug_unique` (`slug`),
  KEY `posts_user_id_foreign` (`user_id`),
  CONSTRAINT `posts_user_id_foreign` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO `posts` (`id`, `title`, `slug`, `content`, `excerpt`, `user_id`, `featured_image`, `is_published`, `published_at`, `created_at`, `updated_at`) VALUES
(1,	'Dolorum impedit incidunt aut nobis.',	'temporibus-praesentium-optio-fugiat-repellendus-necessitatibus-temporibus-blanditiis',	'Cum est ullam dolorem nobis mollitia architecto est. Ipsum labore assumenda tempore. Modi asperiores et non nam. Voluptatem nesciunt vel et amet.\n\nEt a suscipit consequatur repellendus ut. Esse et deleniti autem et est architecto. Distinctio natus voluptatem quos et ea non.\n\nVoluptates rerum rem unde nam aut. In aut rerum quo. Earum temporibus tempore magni architecto dolorem voluptate.',	'Ut quasi similique tempora non maxime neque. Et corrupti doloremque debitis tenetur qui et et. Dolorum rerum pariatur est non sunt et consequuntur enim.',	6,	'https://images.pexels.com/photos/3769167/pexels-photo-3769167.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',	0,	NULL,	'2024-12-20 20:56:02',	'2024-12-20 20:56:02'),
(2,	'Accusantium hic possimus perspiciatis voluptatem.',	'repellendus-odit-facere-dolores-dolores-sapiente-laudantium-alias',	'Et perferendis aut a. Ut aut ad deserunt in fugit ipsum. Non et accusantium amet accusamus cum.\n\nVoluptatem totam optio consequatur rerum ut et tenetur. Recusandae tempore distinctio et aut. Eos veritatis excepturi consectetur voluptas esse voluptate.\n\nOmnis facilis autem nulla laudantium provident. Praesentium officiis error eos amet iste. Qui voluptate recusandae sit modi nihil doloremque.',	'Qui autem aut voluptatibus culpa non. Et voluptas laudantium fugiat explicabo tempora nihil fuga earum. Doloribus quia officiis voluptas et placeat.',	7,	'https://images.pexels.com/photos/8385737/pexels-photo-8385737.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',	0,	NULL,	'2024-12-20 20:56:02',	'2024-12-20 20:56:02'),
(3,	'Maiores asperiores nisi ut vel in.',	'totam-qui-sed-necessitatibus-autem',	'Perferendis quisquam eaque asperiores nihil quod rem. Eligendi reprehenderit et minima repellendus aliquid repudiandae eius quod. Dolor debitis quod ea omnis saepe quisquam inventore.\n\nPossimus consequatur veritatis ut neque qui corporis. Eos dolor quos ut aut et sapiente facere est. Fugiat omnis dolorem nihil culpa velit ut quo.\n\nAb hic rem ipsa et. Occaecati sint fugit eveniet et numquam eos aut. Suscipit adipisci quis aut eaque nisi vel deserunt. Voluptatem nam voluptatem est sed sed alias. Repellat nihil libero magnam ut.',	'Nisi et quae mollitia voluptatum. Eligendi sint veniam nemo illo ut corrupti. In nobis fuga qui asperiores perferendis deleniti libero. Illo nemo vel quo ipsum voluptatem voluptatem dolor.',	8,	'https://images.pexels.com/photos/25626428/pexels-photo-25626428.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',	0,	NULL,	'2024-12-20 20:56:02',	'2024-12-20 20:56:02'),
(4,	'Consequatur possimus animi ducimus ducimus repellat quo ut quis.',	'et-id-quae-veniam-facilis-eius-ex',	'Facilis quisquam praesentium repellat eos et nam est sunt. Perferendis fuga ipsa ut est illum rem. Rerum atque eius ea. Rerum sit rem adipisci suscipit. Nostrum ut dolore quae placeat harum enim ducimus.\n\nAssumenda sequi quaerat et in ut qui tempore. Quia non consequuntur hic doloremque iusto consectetur non. Aut explicabo sapiente delectus excepturi aut. Aut et possimus ut quisquam quasi.\n\nQuo nihil ut quas sit et nemo. Laudantium aut fuga molestias optio assumenda accusantium.',	'Provident quidem et qui numquam. Quis eos modi assumenda perferendis. Rem et voluptatibus est occaecati animi itaque voluptatibus. Ut aliquam vel nihil illo labore iusto.',	9,	'https://images.pexels.com/photos/2911519/pexels-photo-2911519.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',	0,	NULL,	'2024-12-20 20:56:02',	'2024-12-20 20:56:02'),
(5,	'Voluptatem rerum sed voluptas.',	'quisquam-nemo-praesentium-beatae-est-eveniet-nam-debitis-officiis',	'Nobis similique aut quasi amet. Vel omnis dolorem illo. Rerum sapiente praesentium deserunt quos rerum asperiores ex. Assumenda omnis sint animi aliquam unde suscipit perspiciatis.\n\nEx qui vitae rem harum qui sed animi blanditiis. Quibusdam voluptatem accusantium non suscipit ut. Consequatur necessitatibus esse temporibus ratione adipisci eos.\n\nEst quisquam dolorem facere expedita cum ut. Reprehenderit ducimus voluptas qui expedita molestiae eos. Mollitia commodi voluptates quos a vel esse.',	'Sapiente quod vero ea ex. Repudiandae omnis debitis cum consequuntur. Animi neque hic eum voluptas est.',	10,	'https://images.pexels.com/photos/29579034/pexels-photo-29579034.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',	0,	NULL,	'2024-12-20 20:56:02',	'2024-12-20 20:56:02'),
(6,	'Aut id et est aliquam perferendis numquam.',	'fugit-rerum-blanditiis-sint-animi-et',	'Sit sunt iste distinctio quo. Velit ut est minus similique. Eum fugit cumque ipsa ut porro quo quasi.\n\nAliquid ducimus consequuntur eius provident. Maiores doloremque doloremque ut molestiae iusto impedit. Illo suscipit autem aperiam ea et tempora. Et qui dolor accusantium quidem et.\n\nDeserunt consequatur placeat est sunt. Repudiandae voluptas temporibus molestiae optio dolor. Sed fugiat autem rerum pariatur ipsum. Ipsam quibusdam cumque dolorem labore soluta aspernatur aut quam.',	'Sunt impedit alias ut ipsam. Porro sed quas voluptatibus id et labore cum. Fuga enim vero sapiente rem sint.',	11,	'https://images.pexels.com/photos/278887/pexels-photo-278887.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',	0,	NULL,	'2024-12-20 20:56:02',	'2024-12-20 20:56:02'),
(7,	'Delectus cum voluptatem ad cumque.',	'necessitatibus-rem-ad-rerum-et-quod',	'Repellendus dicta facere et enim ad accusantium. Ut cum pariatur et voluptas. Impedit aut quasi qui mollitia. Omnis et eum nihil autem.\n\nBeatae recusandae voluptas hic facere laboriosam. Inventore et sit nulla tenetur. Fugit consequatur magnam doloremque sit ut iste voluptatum.\n\nDolores distinctio alias officiis error. Nihil molestiae nesciunt laboriosam. Ex ipsum in ut.',	'Soluta error et iure facere. Exercitationem occaecati eaque quos repudiandae est alias amet. Tenetur aperiam corporis culpa aut natus eligendi esse. Facere aut ea consequatur aut laboriosam.',	12,	'https://images.pexels.com/photos/7002920/pexels-photo-7002920.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',	0,	NULL,	'2024-12-20 20:56:02',	'2024-12-20 20:56:02'),
(8,	'A sequi sequi blanditiis vel.',	'accusamus-voluptatem-maxime-tempore-esse',	'Placeat voluptates non deserunt quis illum illo. Mollitia delectus voluptatibus sunt cum. Et rerum ut atque quis unde explicabo a.\n\nEt ratione doloribus quia vero. Exercitationem est vel labore odit occaecati nihil. Aspernatur nulla voluptatem non corporis aperiam nesciunt.\n\nDoloremque odit libero placeat excepturi cupiditate dicta suscipit quaerat. Quos illo consequatur et repudiandae aut consectetur nam ut. Nihil expedita saepe veniam minima est. Id non ex illo voluptas commodi suscipit.',	'Perferendis illo impedit beatae. Eos et animi eligendi expedita nihil neque. Nam dolorum nihil voluptatem tempora voluptatem ipsa provident suscipit. Et velit sequi eligendi.',	13,	'https://images.pexels.com/photos/8386138/pexels-photo-8386138.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',	0,	NULL,	'2024-12-20 20:56:02',	'2024-12-20 20:56:02'),
(9,	'Fugit aliquid error architecto repellat occaecati earum.',	'vel-unde-molestias-explicabo-maiores-quia-quasi',	'Saepe ut est commodi repellat illo. Consequatur laboriosam qui nemo numquam. Blanditiis provident est praesentium. Nostrum veritatis id a magni.\n\nAtque nobis est ipsa molestiae vel voluptatem rerum ipsum. Ratione qui dolor officiis autem consequatur aspernatur magnam deleniti. Debitis assumenda voluptas et. Eius tempore ut ut aut est aut. A qui dolor distinctio nisi ex optio sunt.\n\nQui aspernatur ut sunt. Est doloribus fugit omnis tempora. In vel autem autem ut ipsam consequatur. Esse culpa laboriosam blanditiis corrupti.',	'Soluta sint asperiores suscipit tempore consequatur. Voluptatem ducimus amet nihil ab. Deleniti voluptatibus eligendi et nobis consequuntur aliquid aut. Dolor nam sunt ut earum quae et.',	14,	'https://images.pexels.com/photos/9665191/pexels-photo-9665191.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',	0,	NULL,	'2024-12-20 20:56:02',	'2024-12-20 20:56:02'),
(10,	'In et consectetur tenetur voluptatem corrupti quo provident.',	'atque-est-aut-dolore-voluptate-tenetur-eos-molestiae',	'Qui rerum dolorem et minus. Esse impedit eaque facere neque autem necessitatibus voluptates. Neque aperiam labore ut tempore quod.\n\nDolores doloribus quidem minus praesentium libero maxime. Qui ex officiis reiciendis mollitia. Nam explicabo qui voluptas quia consequuntur sit commodi.\n\nDolore aut assumenda maiores occaecati. Qui quo et eius.',	'Dolores autem consequatur exercitationem exercitationem excepturi cumque cumque. Molestiae modi autem rerum quo et. Tempore aperiam veniam sit tempore iusto. Officiis harum quibusdam ut aut aut natus.',	15,	'https://images.pexels.com/photos/7107987/pexels-photo-7107987.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',	0,	NULL,	'2024-12-20 20:56:02',	'2024-12-20 20:56:02');

-- 2024-12-20 15:56:36
