<template>
    <div class="min-h-screen bg-gradient-to-br from-purple-900 to-blue-900 text-white p-8">
        <div class="container mx-auto max-w-4xl bg-white bg-opacity-10 p-8 rounded-lg shadow-lg">
            <h1 class="text-4xl font-bold mb-6 pb-4 border-b-2 border-cyan-300">Privacy Policy</h1>
            <p class="mb-4 text-cyan-300">Last updated: September 07, 2024</p>

            <div class="space-y-6 text-gray-100">
                <p>This Privacy Policy describes Our policies and procedures on the collection, use and disclosure of Your information when You use the Service and tells You about Your privacy rights and how the law protects You.</p>

                <p>We use Your Personal data to provide and improve the Service. By using the Service, You agree to the collection and use of information in accordance with this Privacy Policy. This Privacy Policy has been created with the help of the <a href="https://www.termsfeed.com/privacy-policy-generator/" target="_blank" class="text-cyan-300 hover:underline">Privacy Policy Generator</a>.</p>

                <h2 class="text-2xl font-semibold mt-8 mb-4 text-cyan-300">Interpretation and Definitions</h2>
                <h3 class="text-xl font-semibold mb-2">Interpretation</h3>
                <p>The words of which the initial letter is capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.</p>

                <h3 class="text-xl font-semibold mb-2">Definitions</h3>
                <p>For the purposes of this Privacy Policy:</p>
                <ul class="list-disc pl-6 space-y-2">
                    <li><strong>Account</strong> means a unique account created for You to access our Service or parts of our Service.</li>
                    <li><strong>Affiliate</strong> means an entity that controls, is controlled by or is under common control with a party, where "control" means ownership of 50% or more of the shares, equity interest or other securities entitled to vote for election of directors or other managing authority.</li>
                    <li><strong>Company</strong> (referred to as either "the Company", "We", "Us" or "Our" in this Agreement) refers to Three First Names &amp; Associates, 2811 N Bell Ave #208, Chicago, IL 60618.</li>
                    <li><strong>Cookies</strong> are small files that are placed on Your computer, mobile device or any other device by a website, containing the details of Your browsing history on that website among its many uses.</li>
                    <li><strong>Country</strong> refers to: Illinois, United States</li>
                    <li><strong>Device</strong> means any device that can access the Service such as a computer, a cellphone or a digital tablet.</li>
                    <li><strong>Personal Data</strong> is any information that relates to an identified or identifiable individual.</li>
                    <li><strong>Service</strong> refers to the Website.</li>
                    <li><strong>Service Provider</strong> means any natural or legal person who processes the data on behalf of the Company. It refers to third-party companies or individuals employed by the Company to facilitate the Service, to provide the Service on behalf of the Company, to perform services related to the Service or to assist the Company in analyzing how the Service is used.</li>
                    <li><strong>Usage Data</strong> refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).</li>
                    <li><strong>Website</strong> refers to Three First Names &amp; Associates, accessible from <a href="https://tfnms.co" rel="external nofollow noopener" target="_blank" class="text-cyan-300 hover:underline">tfnms.co</a></li>
                    <li><strong>You</strong> means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.</li>
                </ul>

                <h2 class="text-2xl font-semibold mt-8 mb-4 text-cyan-300">Collecting and Using Your Personal Data</h2>
                <h3 class="text-xl font-semibold mb-2">Types of Data Collected</h3>
                <h4 class="text-lg font-semibold mb-2">Personal Data</h4>
                <p>While using Our Service, We may ask You to provide Us with certain personally identifiable information that can be used to contact or identify You. Personally identifiable information may include, but is not limited to:</p>
                <ul class="list-disc pl-6 space-y-2">
                    <li>Email address</li>
                    <li>First name and last name</li>
                    <li>Phone number</li>
                    <li>Usage Data</li>
                </ul>

                <!-- The rest of the content follows the same structure -->

                <h2 class="text-2xl font-semibold mt-8 mb-4 text-cyan-300">Contact Us</h2>
                <p>If you have any questions about this Privacy Policy, You can contact us:</p>
                <ul class="list-disc pl-6 space-y-2">
                    <li>By email: <a href="mailto:hello@tfnms.co" class="text-cyan-300 hover:underline">hello@tfnms.co</a></li>
                    <li>By phone number: <a href="tel:7737103016" class="text-cyan-300 hover:underline">773 710 3016</a></li>
                </ul>
            </div>
        </div>
    </div>
</template>

<script>
export default {
    name: 'PrivacyPolicy',
    // You can add any necessary component logic here
}
</script>
